-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bills
(
    generated_at timestamp without time zone NOT NULL DEFAULT now(),
    bill_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    bill_ref text COLLATE pg_catalog."default" NOT NULL,
    bill_total double precision,
    CONSTRAINT bills_pkey PRIMARY KEY (bill_uuid)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id serial NOT NULL,
    bill_ref uuid NOT NULL,
    product_name text COLLATE pg_catalog."default" NOT NULL,
    product_price double precision NOT NULL,
    products_backup text COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_mail text COLLATE pg_catalog."default" NOT NULL,
    user_uuid text COLLATE pg_catalog."default" NOT NULL,
    id serial NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_mail),
    CONSTRAINT users_user_uuid_key UNIQUE (user_uuid)
);

ALTER TABLE IF EXISTS public.bills
    ADD CONSTRAINT bills_bill_ref_fkey FOREIGN KEY (bill_ref)
    REFERENCES public.users (user_mail) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT fk_bill_ref FOREIGN KEY (bill_ref)
    REFERENCES public.bills (bill_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_bill_ref_fkey FOREIGN KEY (bill_ref)
    REFERENCES public.bills (bill_uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;