# -*- coding: utf-8 -*-
"""a101

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmSwc92HOYxleIlelURTJnVTgrAKZVLw
"""

#!pip install easyocr
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import easyocr as ocr
import cv2
import numpy as np
import pandas as pd

ocr_motoru = ocr.Reader(['en','tr'])

with open('cagdaş5.jpeg' , 'rb')  as f:
  resim = f.read()

  resim_ham = np.frombuffer(resim, np.uint8)
  resim_cv2 = cv2.imdecode(resim_ham, cv2.IMREAD_COLOR)

# from google.colab.patches import cv2_imshow
# cv2_imshow(resim_cv2)

yazilar = ocr_motoru.readtext(resim)

ettn_bulundu = False
kredi_karti_bulundu = False
yüzde_bulundu = False
ettn_not_bool = False
temp = []

ürünler = []
while True:
  print(40)
  for i, yazi in enumerate(yazilar):
      print(42)
      if ettn_bulundu:
          if kredi_karti_bulundu:
              break
          if i+2 < len(yazilar):
            for item in yazilar[i+2:][0][1].split():

              temp.append(item)
            print(yazilar[i+2:][0][1])
            ürünler.append(yazilar[i+1:][0][1])


      yazi_lower = str(yazi).lower()

      if "ETTN" in yazi:
          ettn_bulundu = True
      if ettn_not_bool == True:
        if "fiş" in yazi_lower:
          ettn_bulundu = True
          ettn_not_bool = False
          kredi_karti_bulundu = False
      if "kredi" in yazi_lower or "nakit" in yazi_lower:
        kredi_karti_bulundu = True
      if i == len(yazilar)-1:
        if ettn_bulundu == False:
          ettn_not_bool = True
  if ettn_not_bool == False:
      break

print(temp)

product = []
price = []
product_bool = False
price_bool = False
comma_bool = False
product_string = ''
price_string = ''
next_bool = False


for count, i in enumerate(temp):
  print(i)

  if (i.isalpha() == True and len(i) != 1):
    product_string = product_string + ' ' + i
    product_bool = True

  elif i.isdigit() == True and product_bool == True:
    product.append(product_string)
    product_string = ''
    product_bool = False
    next_bool = False

  if '*' in i:
    price_string = price_string + i
    price_bool = True

    if ',' not in i:

      if count + 1 < len(temp):

        if ',' not in temp[count + 1]:

          price_string = price_string + ','

  elif (price_bool == True and i.isdigit() == True) or i == ',':
    price_string = price_string + i



  elif i.isalpha() == True and price_bool == True:
    price.append(price_string)
    price_string = ''
    price_bool = False
    next_bool = True


  if i == 'TOPLAM':
    product.append(i)

for i in range(len(product)):
  #print(product[i])
  #print(price[i])
  print(product[i], ':' ,price[i])

df = pd.DataFrame({"ürün" : product[:len(product)] , "fiyat" : price[:len(price)]})

#print(df)
result = df.to_json(orient='records', force_ascii=False)
print(result)